language: go
os: linux

go:
  - 1.13.x

services:
  - docker

before_script:
  - nvm install
  - nvm use
  - yarn install --frozen-lockfile

script:
  - make test
  - yarn test
  - make lint
  - yarn lint
  - make VERSION=$TRAVIS_BRANCH RELEASE=1 release
  - make VERSION=$TRAVIS_BRANCH build-docker
  - make VERSION=$TRAVIS_BRANCH start-docker
  - make test-integration

before_deploy:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

deploy:
  - provider: script
    script: make VERSION=$TRAVIS_BRANCH deploy-docker
    on:
      tags: true

  - provider: releases
    token: $GITHUB_TOKEN
    file: build/smocker.tar.gz
    skip_cleanup: true
    on:
      tags: true
