language: go
os: linux

go:
  - 1.15.x

cache:
  yarn: true
  directories:
    - $GOPATH/pkg/mod

services:
  - docker

addons:
  sonarcloud:
    organization: thiht

# See: https://docs.travis-ci.com/user/sonarcloud/#accessing-full-scm-history
git:
  depth: false

before_script:
  - nvm install
  - nvm use
  - yarn install --frozen-lockfile
  - go mod download

script:
  - make test
  - make test-integration
  - yarn test
  - make coverage
  - make lint
  - yarn lint
  - make VERSION=$TRAVIS_BRANCH RELEASE=1 release
  - make VERSION=$TRAVIS_BRANCH build-docker
  - make VERSION=$TRAVIS_BRANCH start-docker

after_success:
  - sonar-scanner

before_deploy:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

deploy:
  - provider: script
    script: make VERSION=$TRAVIS_BRANCH deploy-docker
    on:
      tags: true

  - provider: releases
    token: $GITHUB_TOKEN
    file: build/smocker.tar.gz
    skip_cleanup: true
    on:
      tags: true
