language: go

go:
  - 1.13.x

services:
  - docker

script:
  - make test
  - make lint
  - make VERSION=$TRAVIS_BRANCH build
  - make VERSION=$TRAVIS_BRANCH build-docker
  - make VERSION=$TRAVIS_BRANCH start-docker
  - make test-integration

before_deploy:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

deploy:
  - provider: script
    script: make VERSION=$TRAVIS_BRANCH deploy-docker
    on:
      tags: true

  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: build/*
    skip_cleanup: true
    on:
      tags: true
