language: generic

services:
  - docker

script:
  - make VERSION=$TRAVIS_TAG build-docker

before_deploy:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

deploy:
  provider: script
  script: make VERSION=$TRAVIS_TAG deploy-docker
  on:
    tags: true
